In [1]:
%load_ext autoreload
%autoreload 2
%cd ../MusicTransformer-tensorflow2.0

from train import train
train(
    '../out/transformer-preprocess',
    './save-transformer-preprocess',
    log_dir='/tmp/logs/transformer-preprocess'
)

/notebooks/src/MusicTransformer-tensorflow2.0
<class Data has "156" files>


W0525 19:47:23.839350 139855294633792 base_layer.py:2064] Layer encoder is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



batch data [array([390., 388., 388., ..., 388., 388., 388.]), array([390., 388., 388., ..., 388., 388., 388.])]
****
batch_x
(2, 1024)
[[390. 388. 388. ... 388. 388. 388.]
 [390. 388. 388. ... 388. 388. 388.]]
min tf.Tensor(388.0, shape=(), dtype=float64)
max tf.Tensor(390.0, shape=(), dtype=float64)
mean tf.Tensor(388.001953125, shape=(), dtype=float64)
batch_y
(2, 1024)
[[388. 388. 388. ... 388. 388. 388.]
 [388. 388. 388. ... 388. 388. 388.]]
min tf.Tensor(388.0, shape=(), dtype=float64)
max tf.Tensor(388.0, shape=(), dtype=float64)
mean tf.Tensor(388.0, shape=(), dtype=float64)
batch data [array([390., 388., 388., ..., 388., 388., 388.]), array([390., 388., 388., ..., 388., 388., 388.])]

Epoch/Batch: 0/0
Train >>>> Loss:    0.0, Accuracy: 0.0009765625
Eval >>>> Loss:    0.0, Accuracy: 0.00048828125
batch data [array([390., 388., 388., ..., 388., 388., 388.]), array([390., 388., 388., ..., 388., 388., 388.])]
****
batch_x
(2, 1024)
[[390. 388. 388. ... 388. 388. 388.]
 [390. 388. 3

KeyboardInterrupt: 